describe('Todo Component', function() {
    beforeEach(() => {
        cy.server()           // enable response stubbing

        cy.route({
            method: 'GET',      // Route all GET requests
            url: 'https://1api.randomuser.me/?nat=us,gb&results=20',    // that have a URL that matches 'https://api.randomuser.me/?nat=us,gb&results=20'
            response: {
                "results":[
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"tracy",
                            "last":"perkins"
                        },
                        "location":{
                            "street":"5253 highfield road",
                            "city":"wolverhampton",
                            "state":"county antrim",
                            "postcode":"U9T 3BY",
                            "coordinates":{
                                "latitude":"10.4416",
                                "longitude":"-63.1216"
                            },
                            "timezone":{
                                "offset":"+2:00",
                                "description":"Kaliningrad, South Africa"
                            }
                        },
                        "email":"tracy.perkins@example.com",
                        "login":{
                            "uuid":"fb884f2f-c5b6-49fb-b842-7d78ca733aef",
                            "username":"crazycat495",
                            "password":"kaitlyn",
                            "salt":"YvRAM0TS",
                            "md5":"a4e364ace082b9e35d934da0575fc470",
                            "sha1":"f13f9048bbc0bc409b359458aa0965a0585eda8d",
                            "sha256":"6b25657406b1ab856ce0f74b74284dfc861f5f108eb1d627042ca2c8b73c80b3"
                        },
                        "dob":{
                            "date":"1988-12-25T05:21:03Z",
                            "age":30
                        },
                        "registered":{
                            "date":"2009-08-27T20:39:37Z",
                            "age":9
                        },
                        "phone":"016973 79918",
                        "cell":"0790-229-325",
                        "id":{
                            "name":"NINO",
                            "value":"EX 45 81 47 F"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/54.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/54.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/54.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"greg",
                            "last":"beck"
                        },
                        "location":{
                            "street":"6497 rolling green rd",
                            "city":"waxahachie",
                            "state":"new york",
                            "postcode":27042,
                            "coordinates":{
                                "latitude":"16.3225",
                                "longitude":"106.3330"
                            },
                            "timezone":{
                                "offset":"-5:00",
                                "description":"Eastern Time (US & Canada), Bogota, Lima"
                            }
                        },
                        "email":"greg.beck@example.com",
                        "login":{
                            "uuid":"22eae6b3-ae0a-4c7b-ba31-6e2c10388fce",
                            "username":"sadswan343",
                            "password":"lekker",
                            "salt":"F9bu0iPj",
                            "md5":"43f206b11cb36df1aa9822c1e8242733",
                            "sha1":"ebedd64c1e52643d6878003b970e152c14b7ab9b",
                            "sha256":"4d906da77a49bd8081c48cd245ae9e6e728b3c9fef10d3aa3de1f5e3fd5a04a4"
                        },
                        "dob":{
                            "date":"1963-08-30T21:46:00Z",
                            "age":55
                        },
                        "registered":{
                            "date":"2011-10-25T18:08:46Z",
                            "age":7
                        },
                        "phone":"(251)-041-2676",
                        "cell":"(955)-451-4657",
                        "id":{
                            "name":"SSN",
                            "value":"587-73-0876"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/41.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/41.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/41.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"mrs",
                            "first":"sofia",
                            "last":"snyder"
                        },
                        "location":{
                            "street":"5305 york road",
                            "city":"salisbury",
                            "state":"somerset",
                            "postcode":"IX70 7FH",
                            "coordinates":{
                                "latitude":"0.5096",
                                "longitude":"-97.2521"
                            },
                            "timezone":{
                                "offset":"+2:00",
                                "description":"Kaliningrad, South Africa"
                            }
                        },
                        "email":"sofia.snyder@example.com",
                        "login":{
                            "uuid":"bdf046c7-3259-4e37-8c4b-ee1dc25b47dc",
                            "username":"silvermouse622",
                            "password":"737373",
                            "salt":"k4rkHwLw",
                            "md5":"c9b0621b9520df9175baac4a90c81fad",
                            "sha1":"7700bf247d7ea6dea3f77c395f69fc9d351be55d",
                            "sha256":"a777d6a3ec35c3845482fe68506c7c1e2762b40ecab583d5608e999e1235e054"
                        },
                        "dob":{
                            "date":"1994-10-25T23:19:41Z",
                            "age":24
                        },
                        "registered":{
                            "date":"2011-10-01T15:51:24Z",
                            "age":7
                        },
                        "phone":"015395 86345",
                        "cell":"0752-798-987",
                        "id":{
                            "name":"NINO",
                            "value":"EE 24 26 51 Z"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/92.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/92.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/92.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"timothy",
                            "last":"lopez"
                        },
                        "location":{
                            "street":"3164 new road",
                            "city":"plymouth",
                            "state":"warwickshire",
                            "postcode":"EV19 0GZ",
                            "coordinates":{
                                "latitude":"46.9738",
                                "longitude":"79.8194"
                            },
                            "timezone":{
                                "offset":"+5:30",
                                "description":"Bombay, Calcutta, Madras, New Delhi"
                            }
                        },
                        "email":"timothy.lopez@example.com",
                        "login":{
                            "uuid":"d8326e25-85db-4c96-9f21-69e35b246447",
                            "username":"whitepeacock811",
                            "password":"nirvana",
                            "salt":"gTtKvWYZ",
                            "md5":"5e75f809eb1f3184b92bc933c87fb392",
                            "sha1":"10ec96d15f042bc772bc38c5c8543eeaa4310962",
                            "sha256":"17088be6b4a95bfc6fa4769a165084c1f3e1863b98fe61b2a38d9bb4dde4e000"
                        },
                        "dob":{
                            "date":"1993-11-19T05:30:34Z",
                            "age":25
                        },
                        "registered":{
                            "date":"2013-10-23T03:34:40Z",
                            "age":5
                        },
                        "phone":"0161 405 1071",
                        "cell":"0724-344-857",
                        "id":{
                            "name":"NINO",
                            "value":"AM 83 05 65 M"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/25.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/25.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/25.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"daniel",
                            "last":"duncan"
                        },
                        "location":{
                            "street":"8522 kingsway",
                            "city":"truro",
                            "state":"shropshire",
                            "postcode":"JU44 7EZ",
                            "coordinates":{
                                "latitude":"-39.0533",
                                "longitude":"-27.7525"
                            },
                            "timezone":{
                                "offset":"-1:00",
                                "description":"Azores, Cape Verde Islands"
                            }
                        },
                        "email":"daniel.duncan@example.com",
                        "login":{
                            "uuid":"8f043e44-81e5-47cf-91b0-435e1af97f3f",
                            "username":"beautifulpeacock335",
                            "password":"yang",
                            "salt":"pUY99nx8",
                            "md5":"8ece3872221348c2c94e93f71b2af55b",
                            "sha1":"a3e90ef567a301438aeb1b13a6f98a17f8f7b686",
                            "sha256":"da28dbbb10f8f7d7c18bb320a0531f5b72d531e4f9e18354785574e1c26d1653"
                        },
                        "dob":{
                            "date":"1952-03-10T03:59:54Z",
                            "age":67
                        },
                        "registered":{
                            "date":"2005-05-05T09:06:43Z",
                            "age":14
                        },
                        "phone":"017683 99900",
                        "cell":"0712-448-363",
                        "id":{
                            "name":"NINO",
                            "value":"EJ 69 35 49 C"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/3.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/3.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/3.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"bruce",
                            "last":"taylor"
                        },
                        "location":{
                            "street":"6123 bollinger rd",
                            "city":"plano",
                            "state":"virginia",
                            "postcode":16788,
                            "coordinates":{
                                "latitude":"-54.5523",
                                "longitude":"-114.1638"
                            },
                            "timezone":{
                                "offset":"+8:00",
                                "description":"Beijing, Perth, Singapore, Hong Kong"
                            }
                        },
                        "email":"bruce.taylor@example.com",
                        "login":{
                            "uuid":"f869acdc-fc51-4fd2-978d-17b344604abf",
                            "username":"blacklion379",
                            "password":"nimrod",
                            "salt":"amoGDVQj",
                            "md5":"1d9ef313df957ef67090eb3c6da388c7",
                            "sha1":"c08a086a0c9ee72f42f98e5332ff4a23ed8a9e57",
                            "sha256":"1d1035ef5937dd621f78ad2f8181648dac09603f1fab4898a42ec70aaeb326af"
                        },
                        "dob":{
                            "date":"1964-05-13T22:17:36Z",
                            "age":55
                        },
                        "registered":{
                            "date":"2009-06-29T05:40:28Z",
                            "age":9
                        },
                        "phone":"(285)-372-8202",
                        "cell":"(756)-083-8124",
                        "id":{
                            "name":"SSN",
                            "value":"376-14-7623"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/34.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/34.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/34.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"ms",
                            "first":"jennie",
                            "last":"jenkins"
                        },
                        "location":{
                            "street":"5026 lakeview st",
                            "city":"erie",
                            "state":"idaho",
                            "postcode":84089,
                            "coordinates":{
                                "latitude":"24.7803",
                                "longitude":"-111.8284"
                            },
                            "timezone":{
                                "offset":"-9:00",
                                "description":"Alaska"
                            }
                        },
                        "email":"jennie.jenkins@example.com",
                        "login":{
                            "uuid":"8f05f2a2-8bd4-4596-8821-623abaf88792",
                            "username":"yellowgoose199",
                            "password":"casino",
                            "salt":"dQgmzwdR",
                            "md5":"81c33d6d053aaaad538e2025e0c4c171",
                            "sha1":"72d44a24c7d31a3e4cd8e72c52899fb63f08fb00",
                            "sha256":"2c5242159530c50fe7fe08c517f3847c02cb895ea5d8886f63a7838b5f1d1211"
                        },
                        "dob":{
                            "date":"1991-04-11T03:04:54Z",
                            "age":28
                        },
                        "registered":{
                            "date":"2006-02-10T23:37:33Z",
                            "age":13
                        },
                        "phone":"(190)-158-0944",
                        "cell":"(832)-550-6438",
                        "id":{
                            "name":"SSN",
                            "value":"696-86-9245"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/34.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/34.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/34.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"neil",
                            "last":"perry"
                        },
                        "location":{
                            "street":"2670 hillcrest rd",
                            "city":"thornton",
                            "state":"north carolina",
                            "postcode":88444,
                            "coordinates":{
                                "latitude":"-11.5388",
                                "longitude":"37.1298"
                            },
                            "timezone":{
                                "offset":"-8:00",
                                "description":"Pacific Time (US & Canada)"
                            }
                        },
                        "email":"neil.perry@example.com",
                        "login":{
                            "uuid":"8c9ecb50-ebba-49dd-a88f-bc32e4285950",
                            "username":"lazyduck629",
                            "password":"golfer1",
                            "salt":"AL6q2EeZ",
                            "md5":"d9f993c40c2e8dd35757245f1e43e924",
                            "sha1":"6c770b35598ef025df8610b1f0be485df055d05a",
                            "sha256":"4645d60a89a3d492450911195700e2035390d867e26c539670a584adc24812a5"
                        },
                        "dob":{
                            "date":"1986-03-05T14:02:34Z",
                            "age":33
                        },
                        "registered":{
                            "date":"2015-04-29T08:14:12Z",
                            "age":4
                        },
                        "phone":"(810)-466-8832",
                        "cell":"(042)-842-6551",
                        "id":{
                            "name":"SSN",
                            "value":"725-53-9162"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/50.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/50.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/50.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"ms",
                            "first":"vicki",
                            "last":"flores"
                        },
                        "location":{
                            "street":"9772 the green",
                            "city":"canterbury",
                            "state":"kent",
                            "postcode":"C5C 6XJ",
                            "coordinates":{
                                "latitude":"45.2307",
                                "longitude":"50.6013"
                            },
                            "timezone":{
                                "offset":"-10:00",
                                "description":"Hawaii"
                            }
                        },
                        "email":"vicki.flores@example.com",
                        "login":{
                            "uuid":"9f9fb254-f837-458e-9551-2d24c3b60be2",
                            "username":"beautifulcat310",
                            "password":"genesis",
                            "salt":"4mHLyjzI",
                            "md5":"ba791b9ec45739d8cd6b4a281de03c1c",
                            "sha1":"3aa0e3c6f23a6f2f97aefc3963ef60897a163fec",
                            "sha256":"725f34e2a4f09b823aec85b1ba7aee4ec371a874c4dfe679d5680efac88d3b72"
                        },
                        "dob":{
                            "date":"1962-11-04T20:35:20Z",
                            "age":56
                        },
                        "registered":{
                            "date":"2006-04-20T18:20:41Z",
                            "age":13
                        },
                        "phone":"017687 50283",
                        "cell":"0708-336-495",
                        "id":{
                            "name":"NINO",
                            "value":"KP 72 68 54 I"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/50.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/50.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/50.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"kirk",
                            "last":"hernandez"
                        },
                        "location":{
                            "street":"9030 oak ridge ln",
                            "city":"fontana",
                            "state":"delaware",
                            "postcode":36857,
                            "coordinates":{
                                "latitude":"-58.1809",
                                "longitude":"145.8332"
                            },
                            "timezone":{
                                "offset":"-9:00",
                                "description":"Alaska"
                            }
                        },
                        "email":"kirk.hernandez@example.com",
                        "login":{
                            "uuid":"00a40c57-5c85-4e1d-a3b2-6fbd94681dbf",
                            "username":"lazyswan865",
                            "password":"madison1",
                            "salt":"FgpyJBLs",
                            "md5":"b4e0477e6d81fa7e149db0a2b52b69d5",
                            "sha1":"67d88fbab95399dc4e364f8309a6205ff1480cdd",
                            "sha256":"0d59f6cb28575494e1c56339d5fb88b3d3b2801160d52c8c9394e2d5cff7f3c6"
                        },
                        "dob":{
                            "date":"1985-10-11T13:28:23Z",
                            "age":33
                        },
                        "registered":{
                            "date":"2014-06-17T12:14:11Z",
                            "age":4
                        },
                        "phone":"(120)-767-6978",
                        "cell":"(644)-705-3966",
                        "id":{
                            "name":"SSN",
                            "value":"519-43-0506"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/56.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/56.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/56.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"miss",
                            "first":"karen",
                            "last":"clarke"
                        },
                        "location":{
                            "street":"4996 windsor road",
                            "city":"sunderland",
                            "state":"tyne and wear",
                            "postcode":"K5 0QQ",
                            "coordinates":{
                                "latitude":"-71.6029",
                                "longitude":"146.1306"
                            },
                            "timezone":{
                                "offset":"0:00",
                                "description":"Western Europe Time, London, Lisbon, Casablanca"
                            }
                        },
                        "email":"karen.clarke@example.com",
                        "login":{
                            "uuid":"539679cb-2d18-4210-abf1-2038841d0168",
                            "username":"heavylion985",
                            "password":"yankees",
                            "salt":"7r7eObhl",
                            "md5":"474deb8d479cd08a824f9b2894d191bb",
                            "sha1":"59901a840bf4c1ad1097ad5c7209f8838faa4f9a",
                            "sha256":"7e0ae2b0c51033360d09e67ff0039e51d6341f3d5200503f35c5b83834f33489"
                        },
                        "dob":{
                            "date":"1985-05-17T08:45:12Z",
                            "age":34
                        },
                        "registered":{
                            "date":"2018-06-15T16:03:48Z",
                            "age":0
                        },
                        "phone":"017684 14706",
                        "cell":"0714-110-073",
                        "id":{
                            "name":"NINO",
                            "value":"RC 15 22 24 X"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/45.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/45.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/45.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"luis",
                            "last":"neal"
                        },
                        "location":{
                            "street":"5582 w 6th st",
                            "city":"desoto",
                            "state":"missouri",
                            "postcode":19392,
                            "coordinates":{
                                "latitude":"80.3029",
                                "longitude":"97.6361"
                            },
                            "timezone":{
                                "offset":"-1:00",
                                "description":"Azores, Cape Verde Islands"
                            }
                        },
                        "email":"luis.neal@example.com",
                        "login":{
                            "uuid":"0c30eab8-f8a5-4196-84bf-dfdc7ec32c80",
                            "username":"purpleduck959",
                            "password":"natalie1",
                            "salt":"te7aBIlX",
                            "md5":"c0a1d7738bb0abb19b26790c2852e917",
                            "sha1":"7970d230d0274df77603a5b7b1076c76da6fdbc1",
                            "sha256":"af56ac2bd0aff64861f47322b06da0f05ee9bcb3e798e78203556351f2480d90"
                        },
                        "dob":{
                            "date":"1963-11-22T14:34:29Z",
                            "age":55
                        },
                        "registered":{
                            "date":"2016-07-10T02:30:39Z",
                            "age":2
                        },
                        "phone":"(293)-101-3418",
                        "cell":"(248)-766-4207",
                        "id":{
                            "name":"SSN",
                            "value":"267-78-5879"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/68.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/68.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/68.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"arthur",
                            "last":"campbell"
                        },
                        "location":{
                            "street":"6684 springfield road",
                            "city":"gloucester",
                            "state":"county armagh",
                            "postcode":"W7J 2NG",
                            "coordinates":{
                                "latitude":"-3.9521",
                                "longitude":"146.5360"
                            },
                            "timezone":{
                                "offset":"-1:00",
                                "description":"Azores, Cape Verde Islands"
                            }
                        },
                        "email":"arthur.campbell@example.com",
                        "login":{
                            "uuid":"93aa1335-ec1c-4356-97d0-05eb02888223",
                            "username":"blackbear391",
                            "password":"hjkl",
                            "salt":"DTQwXenu",
                            "md5":"950fed8da627f56edcd6f685a25147a5",
                            "sha1":"3a605f51899df5dc6c3fe2cb652189f07ef70641",
                            "sha256":"e58d1a1e560e5a54ac5f70c61726e144cc6c2217e7cdbb105bfe296dc2fbf511"
                        },
                        "dob":{
                            "date":"1977-07-16T14:32:34Z",
                            "age":41
                        },
                        "registered":{
                            "date":"2018-02-28T01:25:27Z",
                            "age":1
                        },
                        "phone":"013873 61775",
                        "cell":"0700-993-383",
                        "id":{
                            "name":"NINO",
                            "value":"ML 07 68 35 Q"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/5.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/5.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/5.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"marc",
                            "last":"hernandez"
                        },
                        "location":{
                            "street":"8485 country club rd",
                            "city":"wichita falls",
                            "state":"north carolina",
                            "postcode":52428,
                            "coordinates":{
                                "latitude":"-1.1435",
                                "longitude":"-76.7559"
                            },
                            "timezone":{
                                "offset":"+2:00",
                                "description":"Kaliningrad, South Africa"
                            }
                        },
                        "email":"marc.hernandez@example.com",
                        "login":{
                            "uuid":"a91ff4e8-b57a-4ed1-b595-ccdafcceb47d",
                            "username":"greenduck127",
                            "password":"ernesto",
                            "salt":"2rkoxTwv",
                            "md5":"7ce7370c2b178fecaa33dc64d982bcc4",
                            "sha1":"231f8a9d26a16412daf3d212bca992eaad4a8609",
                            "sha256":"e0df6bd3577b67ae6e12d8af2dc312a9d838be819ec95aa68440a05d3a6561fa"
                        },
                        "dob":{
                            "date":"1981-02-20T15:56:41Z",
                            "age":38
                        },
                        "registered":{
                            "date":"2013-04-22T06:18:41Z",
                            "age":6
                        },
                        "phone":"(128)-350-5557",
                        "cell":"(814)-768-9842",
                        "id":{
                            "name":"SSN",
                            "value":"008-14-2451"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/85.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/85.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/85.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"mrs",
                            "first":"elsie",
                            "last":"hawkins"
                        },
                        "location":{
                            "street":"479 walnut hill ln",
                            "city":"jersey city",
                            "state":"kentucky",
                            "postcode":31595,
                            "coordinates":{
                                "latitude":"9.4020",
                                "longitude":"73.6249"
                            },
                            "timezone":{
                                "offset":"-3:30",
                                "description":"Newfoundland"
                            }
                        },
                        "email":"elsie.hawkins@example.com",
                        "login":{
                            "uuid":"32acc1a6-594b-4ad3-8f44-baaf9a71820b",
                            "username":"happytiger202",
                            "password":"1004",
                            "salt":"yALcAHbb",
                            "md5":"82fa7b5e90e67c6a5ad4c50542183f61",
                            "sha1":"b66038217c23f52eb986906e3e2182cdf2a65e02",
                            "sha256":"f6cb68f5e5fbc73d4f452c10a48bd873f421b36bb69bf34bbfc84df6010e3530"
                        },
                        "dob":{
                            "date":"1966-02-19T19:22:05Z",
                            "age":53
                        },
                        "registered":{
                            "date":"2016-10-16T17:10:08Z",
                            "age":2
                        },
                        "phone":"(093)-766-6796",
                        "cell":"(415)-319-5508",
                        "id":{
                            "name":"SSN",
                            "value":"977-26-1101"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/29.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/29.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/29.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"calvin",
                            "last":"ray"
                        },
                        "location":{
                            "street":"8718 victoria street",
                            "city":"preston",
                            "state":"hampshire",
                            "postcode":"W0 5QA",
                            "coordinates":{
                                "latitude":"-62.5414",
                                "longitude":"-71.2520"
                            },
                            "timezone":{
                                "offset":"-3:30",
                                "description":"Newfoundland"
                            }
                        },
                        "email":"calvin.ray@example.com",
                        "login":{
                            "uuid":"9bacee23-8402-4880-b3ff-06a16545f631",
                            "username":"blackcat801",
                            "password":"right",
                            "salt":"A3FoDvJU",
                            "md5":"d86b479814e7ffc92e6b2a1ba5076324",
                            "sha1":"f925dfbe1497029a1de0867b3bad665e4fa5513a",
                            "sha256":"eae4a63f19985774990d27842485789f41ce2e3789493ac986bb3af40abcbc09"
                        },
                        "dob":{
                            "date":"1972-03-14T02:12:09Z",
                            "age":47
                        },
                        "registered":{
                            "date":"2008-11-15T12:03:35Z",
                            "age":10
                        },
                        "phone":"017684 27323",
                        "cell":"0777-074-382",
                        "id":{
                            "name":"NINO",
                            "value":"MC 24 12 19 C"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/83.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/83.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/83.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"miss",
                            "first":"gina",
                            "last":"west"
                        },
                        "location":{
                            "street":"5765 valley view ln",
                            "city":"eugene",
                            "state":"oklahoma",
                            "postcode":85186,
                            "coordinates":{
                                "latitude":"54.0209",
                                "longitude":"-19.6730"
                            },
                            "timezone":{
                                "offset":"-6:00",
                                "description":"Central Time (US & Canada), Mexico City"
                            }
                        },
                        "email":"gina.west@example.com",
                        "login":{
                            "uuid":"eeebd3b3-be77-43aa-9dee-cb60099176a6",
                            "username":"sadkoala223",
                            "password":"piccolo",
                            "salt":"MB1vECo6",
                            "md5":"2ce52e25dc66adb5e56fe98848ef416a",
                            "sha1":"c7b641ce42373a042878d5970230a4db8bca0b16",
                            "sha256":"c212d7f9ee75203f087287c56745cbff656af548c585f4b5840a589fb085a8bb"
                        },
                        "dob":{
                            "date":"1961-12-25T16:52:58Z",
                            "age":57
                        },
                        "registered":{
                            "date":"2009-11-04T21:15:46Z",
                            "age":9
                        },
                        "phone":"(126)-326-7371",
                        "cell":"(740)-565-7703",
                        "id":{
                            "name":"SSN",
                            "value":"684-92-6327"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/89.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/89.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/89.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"male",
                        "name":{
                            "title":"mr",
                            "first":"terry",
                            "last":"stone"
                        },
                        "location":{
                            "street":"3298 stanley road",
                            "city":"kingston upon hull",
                            "state":"oxfordshire",
                            "postcode":"PU91 0JG",
                            "coordinates":{
                                "latitude":"3.3442",
                                "longitude":"-149.8682"
                            },
                            "timezone":{
                                "offset":"+9:00",
                                "description":"Tokyo, Seoul, Osaka, Sapporo, Yakutsk"
                            }
                        },
                        "email":"terry.stone@example.com",
                        "login":{
                            "uuid":"7782e133-7577-4d8b-be9f-ef7adf72fc94",
                            "username":"whiteelephant753",
                            "password":"vivian",
                            "salt":"iOVJLw5V",
                            "md5":"b155d7739ad8afa63623b292f38728a5",
                            "sha1":"9f4ef39d5793e62bc3cb7e5121525542f029cfd1",
                            "sha256":"8d10792264a84ec689e73bf365fcf2170eed3696870c2ecd0b559089ba14b2ca"
                        },
                        "dob":{
                            "date":"1993-09-16T13:57:42Z",
                            "age":25
                        },
                        "registered":{
                            "date":"2010-06-08T19:49:13Z",
                            "age":8
                        },
                        "phone":"016977 0069",
                        "cell":"0785-508-687",
                        "id":{
                            "name":"NINO",
                            "value":"JR 33 77 06 Y"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/men/89.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/men/89.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/men/89.jpg"
                        },
                        "nat":"GB"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"miss",
                            "first":"kristen",
                            "last":"reyes"
                        },
                        "location":{
                            "street":"3506 valwood pkwy",
                            "city":"glendale",
                            "state":"massachusetts",
                            "postcode":50366,
                            "coordinates":{
                                "latitude":"39.1417",
                                "longitude":"-113.0544"
                            },
                            "timezone":{
                                "offset":"+9:30",
                                "description":"Adelaide, Darwin"
                            }
                        },
                        "email":"kristen.reyes@example.com",
                        "login":{
                            "uuid":"d2f14f47-b662-43c4-99ef-908d518a87b4",
                            "username":"whitegorilla978",
                            "password":"lollipop",
                            "salt":"nOzEJ7Dc",
                            "md5":"9f1a5b70297cdfca2d793f5a376b232e",
                            "sha1":"bac88acfb5cf2ac7194dcded5df2f953572a34ec",
                            "sha256":"70b945b26c2382412ea473f005dbedbf5341655d7de005dee7c7264d53c66da1"
                        },
                        "dob":{
                            "date":"1992-12-19T09:26:54Z",
                            "age":26
                        },
                        "registered":{
                            "date":"2014-10-22T09:21:26Z",
                            "age":4
                        },
                        "phone":"(390)-548-4903",
                        "cell":"(133)-524-4539",
                        "id":{
                            "name":"SSN",
                            "value":"363-32-8861"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/94.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/94.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/94.jpg"
                        },
                        "nat":"US"
                    },
                    {
                        "gender":"female",
                        "name":{
                            "title":"miss",
                            "first":"eleanor",
                            "last":"clarke"
                        },
                        "location":{
                            "street":"9496 the crescent",
                            "city":"ripon",
                            "state":"dorset",
                            "postcode":"S50 4EL",
                            "coordinates":{
                                "latitude":"-51.6435",
                                "longitude":"-100.1795"
                            },
                            "timezone":{
                                "offset":"-3:00",
                                "description":"Brazil, Buenos Aires, Georgetown"
                            }
                        },
                        "email":"eleanor.clarke@example.com",
                        "login":{
                            "uuid":"6d5ec64c-dff3-45ff-8b42-3041afa0a0f6",
                            "username":"brownkoala775",
                            "password":"duncan",
                            "salt":"ELZd742B",
                            "md5":"64cf5e6cf3020ed38632aaafc802902c",
                            "sha1":"e2cbd190f583f7b441cc0e765c826515b5d4f36e",
                            "sha256":"8d7519e0752449fc48cfc2cea1bf2db35b380c4ec27fa5b73ee45c973cc88e28"
                        },
                        "dob":{
                            "date":"1964-07-14T05:19:52Z",
                            "age":54
                        },
                        "registered":{
                            "date":"2005-03-28T21:27:21Z",
                            "age":14
                        },
                        "phone":"019467 61538",
                        "cell":"0702-150-791",
                        "id":{
                            "name":"NINO",
                            "value":"NM 60 66 61 A"
                        },
                        "picture":{
                            "large":"https://randomuser.me/api/portraits/women/85.jpg",
                            "medium":"https://randomuser.me/api/portraits/med/women/85.jpg",
                            "thumbnail":"https://randomuser.me/api/portraits/thumb/women/85.jpg"
                        },
                        "nat":"GB"
                    }
                ],
                "info":{
                    "seed":"83f8f4addad0d040",
                    "results":20,
                    "page":1,
                    "version":"1.2"
                }
            }        // and force the response to be: []
        })

        cy.visit("http://localhost:3000/contacts");
    });

    it('Open Contact app', function() {
        cy.get(".users");

    });

});